name: Feature request
description: "Suggest a new feature or an improvement to an existing one"

labels: enhancement
assignees: BURG3R5

body:
  - type: textarea
    attributes:
      label: Problem description
      description: "A clear and concise description of the problem."
      placeholder: "I'm always frustrated when..."
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed solution
      description: "The solution you'd like to see implemented."
    validations:
      required: true
  - type: textarea
    attributes:
      label: Alternatives considered
      description: "Any alternative solutions or features you've considered."
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional context
      description: "Any other context, examples, or screenshots about the feature request."
    validations:
      required: false
